- name: Make sure Python2 is available
  hosts: idp
  become: True
  gather_facts: False
  tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


- name: Install eduroam Roaming Operator
  hosts: ro
  become: True
  vars_files:
    - group_vars/secrets.yml

  roles:
    - radsecproxy

# - name: Install NewRelic
#   hosts: ro
#   become: True
#   roles:
#     - { role: franklinkim.newrelic, when: play_newrelic == True }
#   vars_files:
#     - group_vars/secrets.yml
#   vars:
#     newrelic_service_state: started
